import React from "react";
import GridSquare from "./GridSqaure";

//Revealed are safe tiles

export const Grid = ({
  gameInPlay,
  revealedTiles,
  mineTiles,
  handleTilePressed,
}) => {
  return (
    <div>
      <div className='"min-h-screen flex items-center justify-center"'>
        <div className="grid grid-cols-5 grid-rows-5 gap-7 ">
          <GridSquare
            tileNumber={1}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(1)}
            mine={mineTiles.includes(1)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={2}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(2)}
            mine={mineTiles.includes(2)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={3}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(3)}
            mine={mineTiles.includes(3)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={4}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(4)}
            mine={mineTiles.includes(4)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={5}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(5)}
            mine={mineTiles.includes(5)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={6}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(6)}
            mine={mineTiles.includes(6)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={7}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(7)}
            mine={mineTiles.includes(7)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={8}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(8)}
            mine={mineTiles.includes(8)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={9}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(9)}
            mine={mineTiles.includes(9)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={10}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(10)}
            mine={mineTiles.includes(10)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={11}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(11)}
            mine={mineTiles.includes(11)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={12}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(12)}
            mine={mineTiles.includes(12)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={13}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(13)}
            mine={mineTiles.includes(13)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={14}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(14)}
            mine={mineTiles.includes(14)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={15}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(15)}
            mine={mineTiles.includes(15)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={16}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(16)}
            mine={mineTiles.includes(16)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={17}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(17)}
            mine={mineTiles.includes(17)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={18}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(18)}
            mine={mineTiles.includes(18)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={19}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(19)}
            mine={mineTiles.includes(19)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={20}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(20)}
            mine={mineTiles.includes(20)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={21}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(21)}
            mine={mineTiles.includes(21)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={22}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(22)}
            mine={mineTiles.includes(22)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={23}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(23)}
            mine={mineTiles.includes(23)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={24}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(24)}
            mine={mineTiles.includes(24)}
            handleTilePressed={handleTilePressed}
          />
          <GridSquare
            tileNumber={25}
            gameInPlay={gameInPlay}
            revealed={revealedTiles.includes(25)}
            mine={mineTiles.includes(25)}
            handleTilePressed={handleTilePressed}
          />
        </div>
      </div>
    </div>
  );
};